app = "batch-code-generator"
primary_region = "sjc"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.checks]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.tcp_checks]
    grace_period = "10s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"

# VM Configuration
[deploy]
  release_command = "npm run build"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Health checks
[[checks]]
  name = "health"
  type = "http"
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "get"
  path = "/api/health"
  protocol = "http"
  tls_skip_verify = false

# Metrics endpoint for Fly.io monitoring
[[checks]]
  name = "metrics"
  type = "http"
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "get"
  path = "/api/metrics"
  protocol = "http"
  tls_skip_verify = false
